<a href="https://colab.research.google.com/github/ForLynda/kaggle_1st/blob/master/Porto_Seguro%E2%80%99s_Safe_Driver_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 캐글과 연동

In [ ]:
!pwd

/content

In [ ]:
# API Token 다운받기
# 다운받은 API Token 업로드 하기
!pip install kaggle
from google.colab import files
files.upload()

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"lynda0128","key":"a33f610b5bfd66306fdb7c2b150d5f93"}'}

\

In [ ]:
# json 파일 옮겨주기
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
# Permission Warning 이 일어나지 않도록 
!chmod 600 ~/.kaggle/kaggle.json
# # json 파일 제대로 업로드 됐는지 확인
# ls -1ha kaggle.json

In [ ]:
# # 본인이 참가한 모든 대회 보기 
# !kaggle competitions list
# 데이터셋 다운로드 받기 - 링크는 그 대회 'Data'에 있음
!kaggle competitions download -c porto-seguro-safe-driver-prediction
# 다운로드 된 것들 다 보기 
!ls

Downloading porto-seguro-safe-driver-prediction.zip to /content
 95% 73.0M/76.5M [00:00<00:00, 126MB/s]
100% 76.5M/76.5M [00:00<00:00, 104MB/s]
kaggle.json  porto-seguro-safe-driver-prediction.zip

In [ ]:
# 다운로드 된 것들 다 보기 
!ls

kaggle.json  porto-seguro-safe-driver-prediction.zip

In [ ]:
!unzip porto-seguro-safe-driver-prediction.zip

Archive:  porto-seguro-safe-driver-prediction.zip
  inflating: sample_submission.csv
  inflating: test.csv
  inflating: train.csv

# 모듈 import

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.utils import shuffle
from sklearn.ensemble import RandomForestClassifier

pd.set_option('display.max_columns',100)

# 데이터

## 데이터 load

In [ ]:
train=pd.read_csv('./train.csv')
test=pd.read_csv('./test.csv')

## 데이터 분석

In [ ]:
train.head()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,0,0,0,0,0,0,11,0,1,0,0.7,0.2,0.718070,10,1,-1,0,1,4,1,0,0,1,12,2,0.400000,0.883679,0.370810,3.605551,0.6,0.5,0.2,3,1,10,1,10,1,5,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,0,0,0,0,0,0,3,0,0,1,0.8,0.4,0.766078,11,1,-1,0,-1,11,1,1,2,1,19,3,0.316228,0.618817,0.388716,2.449490,0.3,0.1,0.3,2,1,9,5,8,1,7,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.0,0.0,-1.000000,7,1,-1,0,-1,14,1,1,2,1,60,1,0.316228,0.641586,0.347275,3.316625,0.5,0.7,0.1,2,2,9,1,8,2,7,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,8,1,0,0,0.9,0.2,0.580948,7,1,0,0,1,11,1,1,3,1,104,1,0.374166,0.542949,0.294958,2.000000,0.6,0.9,0.1,2,4,7,1,8,4,2,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,0,0,0,0,0,0,9,1,0,0,0.7,0.6,0.840759,11,1,-1,0,-1,14,1,1,2,1,82,3,0.316070,0.565832,0.365103,2.000000,0.4,0.6,0.0,2,2,6,3,10,2,12,3,1,1,3,0,0,0,1,1,0

In [ ]:
train.tail()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
595207,1488013,0,3,1,10,0,0,0,0,0,1,0,0,0,0,0,13,1,0,0,0.5,0.3,0.692820,10,1,-1,0,1,1,1,1,0,1,31,3,0.374166,0.684631,0.385487,2.645751,0.4,0.5,0.3,3,0,9,0,9,1,12,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,1,0,0,0,0,0,6,1,0,0,0.9,0.7,1.382027,9,1,-1,0,-1,15,0,0,2,1,63,2,0.387298,0.972145,-1.000000,3.605551,0.2,0.2,0.0,2,4,8,6,8,2,12,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,0,0,0,0,0,0,12,1,0,0,0.9,0.2,0.659071,7,1,-1,0,-1,1,1,1,2,1,31,3,0.397492,0.596373,0.398748,1.732051,0.4,0.0,0.3,3,2,7,4,8,0,10,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.9,0.4,0.698212,11,1,-1,0,-1,11,1,1,2,1,101,3,0.374166,0.764434,0.384968,3.162278,0.0,0.7,0.0,4,0,9,4,9,2,11,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,0,0,0,0,0,0,7,1,0,0,0.1,0.2,-1.000000,7,0,-1,0,-1,0,1,0,2,1,34,2,0.400000,0.932649,0.378021,3.741657,0.4,0.0,0.5,2,3,10,4,10,2,5,4,4,3,8,0,1,0,0,0,0

In [ ]:
train.shape

(595212, 59)

In [ ]:
train.drop_duplicates()
train.shape

(595212, 59)

In [ ]:
test.shape

(892816, 58)

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 59 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              595212 non-null  int64
 1   target          595212 non-null  int64
 2   ps_ind_01       595212 non-null  int64
 3   ps_ind_02_cat   595212 non-null  int64
 4   ps_ind_03       595212 non-null  int64
 5   ps_ind_04_cat   595212 non-null  int64
 6   ps_ind_05_cat   595212 non-null  int64
 7   ps_ind_06_bin   595212 non-null  int64
 8   ps_ind_07_bin   595212 non-null  int64
 9   ps_ind_08_bin   595212 non-null  int64
 10  ps_ind_09_bin   595212 non-null  int64
 11  ps_ind_10_bin   595212 non-null  int64
 12  ps_ind_11_bin   595212 non-null  int64
 13  ps_ind_12_bin   595212 non-null  int64
 14  ps_ind_13_bin   595212 non-null  int64
 15  ps_ind_14       595212 non-null  int64
 16  ps_ind_15       595212 non-null  int64
 17  ps_ind_16_bin   595212 non-null  int64
 18  ps_ind_17_bin   595212 non-null  int64
 19  ps_ind_18_bin   595212 non-null  int64
 20  ps_reg_01       595212 non-null  float64
 21  ps_reg_02       595212 non-null  float64
 22  ps_reg_03       595212 non-null  float64
 23  ps_car_01_cat   595212 non-null  int64
 24  ps_car_02_cat   595212 non-null  int64
 25  ps_car_03_cat   595212 non-null  int64
 26  ps_car_04_cat   595212 non-null  int64
 27  ps_car_05_cat   595212 non-null  int64
 28  ps_car_06_cat   595212 non-null  int64
 29  ps_car_07_cat   595212 non-null  int64
 30  ps_car_08_cat   595212 non-null  int64
 31  ps_car_09_cat   595212 non-null  int64
 32  ps_car_10_cat   595212 non-null  int64
 33  ps_car_11_cat   595212 non-null  int64
 34  ps_car_11       595212 non-null  int64
 35  ps_car_12       595212 non-null  float64
 36  ps_car_13       595212 non-null  float64
 37  ps_car_14       595212 non-null  float64
 38  ps_car_15       595212 non-null  float64
 39  ps_calc_01      595212 non-null  float64
 40  ps_calc_02      595212 non-null  float64
 41  ps_calc_03      595212 non-null  float64
 42  ps_calc_04      595212 non-null  int64
 43  ps_calc_05      595212 non-null  int64
 44  ps_calc_06      595212 non-null  int64
 45  ps_calc_07      595212 non-null  int64
 46  ps_calc_08      595212 non-null  int64
 47  ps_calc_09      595212 non-null  int64
 48  ps_calc_10      595212 non-null  int64
 49  ps_calc_11      595212 non-null  int64
 50  ps_calc_12      595212 non-null  int64
 51  ps_calc_13      595212 non-null  int64
 52  ps_calc_14      595212 non-null  int64
 53  ps_calc_15_bin  595212 non-null  int64
 54  ps_calc_16_bin  595212 non-null  int64
 55  ps_calc_17_bin  595212 non-null  int64
 56  ps_calc_18_bin  595212 non-null  int64
 57  ps_calc_19_bin  595212 non-null  int64
 58  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(49)
memory usage: 267.9 MB

### MEGADATA만들어서 데이터 종류별로 나누기

In [ ]:
data=[]
for f in train.columns :
  if f =='target':
    role='target'
  elif f=='id':
    role='id'
  else:
    role='input'

  if 'bin' in f or f=='target':
    level='binary'
  elif 'cat' in f or f=='id':
    level ='nominal'
  elif train[f].dtype==float:
    level='interval'
  elif train[f].dtype==int:
    level='ordinal'
  
  keep=True
  if f=='id':
    keep=False
  dtype=train[f].dtype

  f_dict={
      'varname' : f,
      'role':role,
      'level':level,
      'keep':keep,
      'dtype':dtype
  }
  data.append(f_dict)
meta=pd.DataFrame(data,columns=['varname','role','level','keep','dtype'])
meta.set_index('varname',inplace=True)

In [ ]:
meta

                  role     level   keep    dtype
varname
id                  id   nominal  False    int64
target          target    binary   True    int64
ps_ind_01        input   ordinal   True    int64
ps_ind_02_cat    input   nominal   True    int64
ps_ind_03        input   ordinal   True    int64
ps_ind_04_cat    input   nominal   True    int64
ps_ind_05_cat    input   nominal   True    int64
ps_ind_06_bin    input    binary   True    int64
ps_ind_07_bin    input    binary   True    int64
ps_ind_08_bin    input    binary   True    int64
ps_ind_09_bin    input    binary   True    int64
ps_ind_10_bin    input    binary   True    int64
ps_ind_11_bin    input    binary   True    int64
ps_ind_12_bin    input    binary   True    int64
ps_ind_13_bin    input    binary   True    int64
ps_ind_14        input   ordinal   True    int64
ps_ind_15        input   ordinal   True    int64
ps_ind_16_bin    input    binary   True    int64
ps_ind_17_bin    input    binary   True    int64
ps_ind_18_bin    input    binary   True    int64
ps_reg_01        input  interval   True  float64
ps_reg_02        input  interval   True  float64
ps_reg_03        input  interval   True  float64
ps_car_01_cat    input   nominal   True    int64
ps_car_02_cat    input   nominal   True    int64
ps_car_03_cat    input   nominal   True    int64
ps_car_04_cat    input   nominal   True    int64
ps_car_05_cat    input   nominal   True    int64
ps_car_06_cat    input   nominal   True    int64
ps_car_07_cat    input   nominal   True    int64
ps_car_08_cat    input   nominal   True    int64
ps_car_09_cat    input   nominal   True    int64
ps_car_10_cat    input   nominal   True    int64
ps_car_11_cat    input   nominal   True    int64
ps_car_11        input   ordinal   True    int64
ps_car_12        input  interval   True  float64
ps_car_13        input  interval   True  float64
ps_car_14        input  interval   True  float64
ps_car_15        input  interval   True  float64
ps_calc_01       input  interval   True  float64
ps_calc_02       input  interval   True  float64
ps_calc_03       input  interval   True  float64
ps_calc_04       input   ordinal   True    int64
ps_calc_05       input   ordinal   True    int64
ps_calc_06       input   ordinal   True    int64
ps_calc_07       input   ordinal   True    int64
ps_calc_08       input   ordinal   True    int64
ps_calc_09       input   ordinal   True    int64
ps_calc_10       input   ordinal   True    int64
ps_calc_11       input   ordinal   True    int64
ps_calc_12       input   ordinal   True    int64
ps_calc_13       input   ordinal   True    int64
ps_calc_14       input   ordinal   True    int64
ps_calc_15_bin   input    binary   True    int64
ps_calc_16_bin   input    binary   True    int64
ps_calc_17_bin   input    binary   True    int64
ps_calc_18_bin   input    binary   True    int64
ps_calc_19_bin   input    binary   True    int64
ps_calc_20_bin   input    binary   True    int64

In [ ]:
meta[(meta.level=='nominal') & (meta.keep)].index

Index(['ps_ind_02_cat', 'ps_ind_04_cat', 'ps_ind_05_cat', 'ps_car_01_cat',
       'ps_car_02_cat', 'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat',
       'ps_car_06_cat', 'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat',
       'ps_car_10_cat', 'ps_car_11_cat'],
      dtype='object', name='varname')

In [ ]:
pd.DataFrame({'count':meta.groupby(['role','level'])['role'].size()}).reset_index()

     role     level  count
0      id   nominal      1
1   input    binary     17
2   input  interval     10
3   input   nominal     14
4   input   ordinal     16
5  target    binary      1

### Ordinal, Binary로 나눠서 결측값, inteval variance 확인

In [ ]:
#Ordinal Variables
v=meta[(meta.level=='interval')&(meta.keep)].index
train[v].describe()

,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.610991,0.439184,0.551102,0.379945,0.813265,0.276256,3.065899,0.449756,0.449589,0.449849
std,0.287643,0.404264,0.793506,0.058327,0.224588,0.357154,0.731366,0.287198,0.286893,0.287153
min,0.000000,0.000000,-1.000000,-1.000000,0.250619,-1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.400000,0.200000,0.525000,0.316228,0.670867,0.333167,2.828427,0.200000,0.200000,0.200000
50%,0.700000,0.300000,0.720677,0.374166,0.765811,0.368782,3.316625,0.500000,0.400000,0.500000
75%,0.900000,0.600000,1.000000,0.400000,0.906190,0.396485,3.605551,0.700000,0.700000,0.700000
max,0.900000,1.800000,4.037945,1.264911,3.720626,0.636396,3.741657,0.900000,0.900000,0.900000

In [ ]:
#Binary Variables
v=meta[(meta.level=='binary')&(meta.keep)].index
train[v].describe()

,target,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.036448,0.393742,0.257033,0.163921,0.185304,0.000373,0.001692,0.009439,0.000948,0.660823,0.121081,0.153446,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,0.187401,0.488579,0.436998,0.370205,0.388544,0.019309,0.041097,0.096693,0.030768,0.473430,0.326222,0.360417,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# binary에서 target값을 보면, 1이 3.65%로 매우 적은 것을 알 수 있다. 
# 이를 imbalanced data라고 하는데, 이를 해결해야한다. 
# 다른 분이랑 했을 때 imbalanced class는 정규화를 안 시켜도 된다. 특히 XGBoost는 내부적으로 imbalanced training이 되지 않도록 한다
# 다만 여기서는 XGboost를 사용하지 않기 때문에, imbalanced 문제를 해결해야한다.

### imbalanced data 조정

In [ ]:
desired_apriori=0.10
idx_0=train[train.target==0].index
idx_1=train[train.target==1].index

nb_0=len(train.loc[idx_0])
nb_1=len(train.loc[idx_1])

undersampling_rate=((1-desired_apriori)*nb_1/(nb_0*desired_apriori))
undersampled_nb_0=int(undersampling_rate*nb_0)
print('Rate to undersample records with target=0: {}'.format(undersampling_rate))
print('Number of records with target=0 after undersampling:{}'.format(undersampled_nb_0))

undersampled_idx=shuffle(idx_0,random_state=37,n_samples=undersampled_nb_0)

idx_list=list(undersampled_idx) + list(idx_1)
train=train.loc[idx_list].reset_index(drop=True)

Rate to undersample records with target=0: 0.34043569687437886
Number of records with target=0 after undersampling:195246

### 결측값 확인

In [ ]:
vars_with_missing=[]

for f in train.columns :
  missings = train[train[f]==-1][f].count()
  if missings > 0 :
    vars_with_missing.append(f)
    missings_perc = missings/train.shape[0]
    print('Variable {} has records ({:.2%}) with missing values'.format(f,missings, missings_perc))

  print('In total, there are {} variables with missing values'.format(len(vars_with_missing)))

In total, there are 0 variables with missing values
In total, there are 0 variables with missing values
In total, there are 0 variables with missing values
Variable ps_ind_02_cat has records (10300.00%) with missing values
In total, there are 1 variables with missing values
In total, there are 1 variables with missing values
Variable ps_ind_04_cat has records (5100.00%) with missing values
In total, there are 2 variables with missing values
Variable ps_ind_05_cat has records (225600.00%) with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
In total, there are 3 variables with missing values
Variable ps_reg_03 has records (3858000.00%) with missing values
In total, there are 4 variables with missing values
Variable ps_car_01_cat has records (6200.00%) with missing values
In total, there are 5 variables with missing values
Variable ps_car_02_cat has records (200.00%) with missing values
In total, there are 6 variables with missing values
Variable ps_car_03_cat has records (14836700.00%) with missing values
In total, there are 7 variables with missing values
In total, there are 7 variables with missing values
Variable ps_car_05_cat has records (9602600.00%) with missing values
In total, there are 8 variables with missing values
In total, there are 8 variables with missing values
Variable ps_car_07_cat has records (443100.00%) with missing values
In total, there are 9 variables with missing values
In total, there are 9 variables with missing values
Variable ps_car_09_cat has records (23000.00%) with missing values
In total, there are 10 variables with missing values
In total, there are 10 variables with missing values
In total, there are 10 variables with missing values
Variable ps_car_11 has records (100.00%) with missing values
In total, there are 11 variables with missing values
In total, there are 11 variables with missing values
In total, there are 11 variables with missing values
Variable ps_car_14 has records (1572600.00%) with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values
In total, there are 12 variables with missing values

In [ ]:
vars_to_drop=['ps_car_03_cat','ps_car_05_cat']
train.drop(vars_to_drop, inplace=True, axis=1)
meta.loc[(vars_to_drop),'keep']=False


# imputer = SimpleImputer(strategy="most_frequent")
mean_imp=SimpleImputer(missing_values=-1, strategy='mean')
mode_imp=SimpleImputer(missing_values=-1,strategy='most_frequent')
train['ps_reg_03']=mean_imp.fit_transform(train[['ps_reg_03']]).ravel()
train['ps_car_12']=mean_imp.fit_transform(train[['ps_car_12']]).ravel()
train['ps_car_14']=mean_imp.fit_transform(train[['ps_car_14']]).ravel()
train['ps_car_11']=mode_imp.fit_transform(train[['ps_car_11']]).ravel()